---
version: '3'
services:
  nautobot:
    build:
      args:
        GRIMLOCK_VERSION: "${GRIMLOCK_VERSION}"
        GRIMLOCK_SRC_URL: "${GRIMLOCK_SRC_URL}"
        nautobot_ver: "${GRIMLOCK_VERSION}"
        python_ver: "${PYTHON_VER}"
      context: ../
      dockerfile: development/Dockerfile
    image: "ntc-nautobot-plugin-metrics-ext/nautobot:${NAUTOBOT_VER}-py${PYTHON_VER}"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./dev.env
    volumes:
      - ./configuration.py:/opt/nautobot/netbox/netbox/configuration.py
      - ./example_reports:/opt/nautobot/netbox/reports
      - ../nautobot_metrics_ext:/source/nautobot_metrics_ext
      - ../:/source
    tty: true
  worker:
    build:
      args:
        GRIMLOCK_VERSION: "${GRIMLOCK_VERSION}"
        GRIMLOCK_SRC_URL: "${GRIMLOCK_SRC_URL}"
        nautobot_ver: "${GRIMLOCK_VERSION}"
        python_ver: "${PYTHON_VER}"
      context: ../
      dockerfile: development/Dockerfile
    image: "ntc-nautobot-plugin-metrics-ext/nautobot:${NAUTOBOT_VER}-py${PYTHON_VER}"
    command: sh -c "python manage.py rqworker"
    depends_on:
      - nautobot
    env_file:
      - ./dev.env
    volumes:
      - ./configuration.py:/opt/nautobot/netbox/netbox/configuration.py
      - ./example_reports:/opt/nautobot/netbox/reports
      - ../nautobot_metrics_ext:/source/nautobot_metrics_ext
    tty: true
  postgres:
    image: postgres:10
    env_file: dev.env
    volumes:
      - pgdata_nautobot_metrics_ext:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    command:
      - sh
      - -c  # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD  ## $$ because of docker-compose
    env_file: ./dev.env
volumes:
  pgdata_nautobot_metrics_ext:
