{
 "title": "Nautobot Application Metrics",
 "description": "Nautobot Application Dashboard",
 "tags": [
  "nautobot",
  "app_metrics"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sites",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nautobot_model_count{name=\"Site\"}"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nautobot_model_count{name=\"Device\"}"
    }
   ]
  },
  {
   "title": "Racks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nautobot_model_count{name=\"Rack\"}"
    }
   ]
  },
  {
   "title": "Prefixes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nautobot_model_count{name=\"Prefix\"}"
    }
   ]
  },
  {
   "title": "IP Addresses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nautobot_model_count{name=\"IPAddress\"}"
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nautobot_app_metrics_processing_ms"
    }
   ]
  },
  {
   "title": "Report Summary",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(status) (nautobot_report_stats)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Job Results",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nautobot_queue_number_jobs{name=\"default\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Report Summary",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nautobot_report_stats\n", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Job Results",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nautobot_queue_number_jobs{name=\"default\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}